Wrote test cases for merger_32 and merger_16

diff --git a/verilog/Makefile b/verilog/Makefile
--- a/verilog/Makefile
+++ b/verilog/Makefile
@@ -26,6 +26,8 @@ data : datagen
 	./datagen 2 $(LIST_INPUT_SIZE) 1 8; \
 	./datagen 256 16 1; \
 	./datagen 1 128 1 1 2; \
+	./datagen 2 16 1 16; \
+	./datagen 2 16 1 32; \
 	cat ans_16_128.txt > ans_16_128_gl2.txt; \
 	cat ans_16_128.txt >> ans_16_128_gl2.txt; \
 	cat ans_16_128_gl2.txt > ans_16_128_gl4.txt; \
@@ -61,6 +63,12 @@ compile_merger_4 : data FIFO.v MERGER_4.v CONTROL.v BITONIC_NETWORK_8.v  MERGER_
 
 compile_merger_8 : data FIFO.v MERGER_8.v CONTROL.v BITONIC_NETWORK_16.v  MERGER_8_tb.v
 	$(VERILOG) -o merger_8 FIFO.v MERGER_8.v CONTROL.v BITONIC_NETWORK_16.v  MERGER_8_tb.v;
+
+compile_merger_16 : data FIFO.v MERGER_16.v CONTROL.v BITONIC_NETWORK_32.v  MERGER_16_tb.v
+	$(VERILOG) -o merger_16 FIFO.v MERGER_16.v CONTROL.v BITONIC_NETWORK_32.v  MERGER_16_tb.v;
+
+compile_merger_32 : data FIFO.v MERGER_32.v CONTROL.v BITONIC_NETWORK_64.v  MERGER_32_tb.v
+	$(VERILOG) -o merger_32 FIFO.v MERGER_32.v CONTROL.v BITONIC_NETWORK_64.v  MERGER_32_tb.v;
 
 compile_tree_P1_L8 : data FIFO.v MERGER.v CONTROL.v BITONIC_NETWORK.v MERGER_TREE_P1_L8_auto.v MERGER_TREE_P1_L8_AUTOMATIC_tb.v
 	$(VERILOG) -o tree_P1_L8 FIFO.v MERGER.v CONTROL.v BITONIC_NETWORK.v MERGER_TREE_P1_L8_auto.v MERGER_TREE_P1_L8_AUTOMATIC_tb.v;
@@ -98,19 +106,25 @@ compile_tree_P1_L128 : FIFO.v MERGER.v CONTROL.v BITONIC_NETWORK.v MERGER_TREE_P
 sim_coupler : compile_coupler
 	$(VVP) coupler
 
-sim_merger_1 : compile_merger_1 merger
+sim_merger_1 : compile_merger_1 
 	$(VVP) merger_1
 
-sim_merger_2 : compile_merger_2 merger
+sim_merger_2 : compile_merger_2 
 	$(VVP) merger_2
 
-sim_merger_4 : compile_merger_4 merger
+sim_merger_4 : compile_merger_4 
 	$(VVP) merger_4
 
-sim_merger_8 : compile_merger_8 merger
+sim_merger_8 : compile_merger_8 
 	$(VVP) merger_8
 
-sim_tree_P1_L8 : compile_tree_P1_L8 merger
+sim_merger_16 : compile_merger_16
+	$(VVP) merger_16
+
+sim_merger_32 : compile_merger_32
+	$(VVP) merger_32
+
+sim_tree_P1_L8 : compile_tree_P1_L8
 	$(VVP) tree_P1_L8;
 
 sim_tree_P2_L8 : compile_tree_P2_L8 tree_P2_L8
@@ -162,6 +176,14 @@ filter_output_merger_4 : sim_merger_4 data
 filter_output_merger_8 : sim_merger_8 data
 	sed '/^0000000000000000000000000000000000000000000000000000000000000000$$/d' out_2_128_8.txt > out_no_zeros_2_128_8.txt
 	sed '/^0000000000000000000000000000000000000000000000000000000000000000$$/d' ans_2_128_8.txt > ans_no_zeros_2_128_8.txt
+
+filter_output_merger_16 : sim_merger_16 data
+	sed '/^00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000$$/d' out_2_16_16.txt > out_no_zeros_2_16_16.txt
+	sed '/^00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000$$/d' ans_2_16_16.txt > ans_no_zeros_2_16_16.txt
+
+filter_output_merger_32 : sim_merger_32 data
+	sed '/^0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000$$/d' out_2_16_32.txt > out_no_zeros_2_16_32.txt
+	sed '/^0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000$$/d' ans_2_16_32.txt > ans_no_zeros_2_16_32.txt
 
 filter_output_tree_P1_L8 : data sim_tree_P1_L8
 	sed '/^00000000$$/d' out_16_128.txt > out_no_zeros_16_128.txt
@@ -233,6 +255,20 @@ test_merger_8 : data compile_merger_8 sim_merger_8 filter_output_merger_8 out_no
 		echo 'ERROR! OUTPUT MISMATCH FOR TEST MERGER_8' 1>&2; \
 	else \
 		echo 'SUCESS! merger_8' 1>&2; \
+	fi
+
+test_merger_16 : data compile_merger_16 sim_merger_16 filter_output_merger_16 out_no_zeros_2_16_16.txt ans_no_zeros_2_16_16.txt merger
+	if [[ $$(diff -u out_no_zeros_2_16_16.txt ans_no_zeros_2_16_16.txt) ]]; then \
+		echo 'ERROR! OUTPUT MISMATCH FOR TEST MERGER_16' 1>&2; \
+	else \
+		echo 'SUCESS! merger_16' 1>&2; \
+	fi
+
+test_merger_32 : data compile_merger_32 sim_merger_32 filter_output_merger_32 out_no_zeros_2_16_32.txt ans_no_zeros_2_16_32.txt merger
+	if [[ $$(diff -u out_no_zeros_2_16_32.txt ans_no_zeros_2_16_32.txt) ]]; then \
+		echo 'ERROR! OUTPUT MISMATCH FOR TEST MERGER_32' 1>&2; \
+	else \
+		echo 'SUCESS! merger_32' 1>&2; \
 	fi
 
 test_tree_P1_L8 : compile_tree_P1_L8 filter_output_tree_P1_L8 out_no_zeros_16_128.txt ans_no_zeros_16_128.txt sim_tree_P1_L8 merger 
